### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [Clever/underscore.deep#28]
Hey there!

I belong to an open source security research community, and a member (@sampaguitas) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by mcab** [comment]
Hi there! You can reach out to `security@clever.com` about this.

**Comment by JamieSlome** [comment]
@mcab - thanks for your response!

@sampaguitas just reached out, but just for reference, the report can be found directly here:
https://huntr.dev/bounties/23204932-72b2-419d-b5f0-34a130752d82/

It is currently private and only accessible to maintainers with repository write permissions 👍

**Comment by mcab** [comment]
Hi! This should be resolved with https://github.com/Clever/underscore.deep/security/advisories/GHSA-8j79-hfj5-f2xm.

I'll reach out to @Sampaguitas on huntr.dev for further follow up. Thank you for bringing this to our attention!

**Comment by JamieSlome** [comment]
@mcab - appreciate your diligence and support here!

Are we able to add the report [URL](https://huntr.dev/bounties/23204932-72b2-419d-b5f0-34a130752d82/) to the GHSA?

**Comment by mcab** [comment]
@JamieSlome - I've added the report URL to the bottom of https://github.com/Clever/underscore.deep/security/advisories/GHSA-8j79-hfj5-f2xm.
